Detect if fzf is not present

diff --git a/git-fza b/git-fza
--- a/git-fza
+++ b/git-fza
@@ -6,7 +6,8 @@ help() {
   echo "Usage: git fza <path>"
 }
 
-# TODO: Detect if fzf is not present, and throw error!
+command -v fzf >/dev/null 2>&1 || { echo >&2 "fzf is required but not installed (https://github.com/junegunn/fzf)"; exit 1; }
+
 if [ "$#" -ne 1 ]; then
     help
 fi
